export const INSERIR_DADOS_PROPOSTA = 'INSERIR_DADOS_PROPOSTA'
export const FIND_SERVICOS_POR_TIPO_EVENTO = 'FIND_SERVICOS_POR_TIPO_EVENTO';
export const SELECIONAR_SERVICO = 'SELECIONAR_SERVICO';
export const APAGAR_DADOS_PROPOSTA = 'APAGAR_DADOS_PROPOSTA';
export const RECEBER_PROPOSTA_EMAIL = 'RECEBER_PROPOSTA_EMAIL';
